name: dscaption
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  path_provider: ^2.0.11
  flutter_image: ^4.0.0
  clipboard: ^0.1.3
  open_file: ^3.2.1
  image_picker: ^0.8.4+4
  file_picker: ^5.0.0
  tflite_flutter: ^0.11.0
  image: ^4.3.0

flutter:
  uses-material-design: true
